//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEFDFCrudWebsiteDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public Nullable<int> DeptID { get; set; }
    
        public virtual tblDepartment tblDepartment { get; set; }
        public virtual tblDepartment tblDepartment1 { get; set; }
    }
}
